package com.certoclav.certoscale.database;


import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import org.json.JSONObject;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "item")
public class Item {

	// id is generated by the database and set on the object automatically


	Item(){

	}


	public int getItem_id() {
		return item_id;
	}

	@DatabaseField(generatedId = true, columnName = "item_id")
	private int item_id;


	public String getItemJson() {
		return itemJson;
	}

	public void setItemJson(String itemJson) {
		this.itemJson = itemJson;
	}

	@DatabaseField(columnName = "item_json")
	private String itemJson;

	public String generateItemJson(String name, Double weight,Double Cost, String articleNumber){
		JSONObject jsonObjectItem = new JSONObject();

		try {
			jsonObjectItem.put("name", name).put("weight", weight).put("Cost",Cost).put("artno",articleNumber);
		}catch (Exception e){
			e.printStackTrace();
		}
		return jsonObjectItem.toString();
	}

	public Item(String itemJson) {

		this.itemJson = itemJson;


	}
	public Item(String cloudId, String name, Double weight,Double Cost, String articleNumber) {
		this.cloudId = cloudId;
		this.itemJson = generateItemJson(name, weight,Cost, articleNumber);
	}

	@DatabaseField(columnName = "cloud_id")
	private String cloudId;

	public String getItemCloudId() {
		String retVal = "";

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			retVal = recipeJson.getString("_id");
		}catch (Exception e){
			retVal = "";
		}
		return retVal;

	}


	public String getItemArticleNumber() {
		String retVal = "";

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			retVal = recipeJson.getString("artno");
		}catch (Exception e){
			e.printStackTrace();
		}
		return retVal;

	}


	public String getName() {
		String retVal = "";

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			retVal = recipeJson.getString("name");
		}catch (Exception e){
			e.printStackTrace();
		}
		return retVal;

	}


	public void setWeight(Double weight) {

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			recipeJson.put("weight",weight);
			itemJson = recipeJson.toString();
		}catch (Exception e){
			e.printStackTrace();
		}


	}


	public void setCost(Double Cost) {

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			recipeJson.put("Cost",Cost);
			itemJson = recipeJson.toString();
		}catch (Exception e){
			e.printStackTrace();
		}


	}


	public void setName(String name) {

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			recipeJson.put("name",name);
			itemJson = recipeJson.toString();
		}catch (Exception e){
			e.printStackTrace();
		}


	}

	public Double getWeight() {
		Double retVal = 0d;

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			retVal = recipeJson.getDouble("weight");
		}catch (Exception e){
			e.printStackTrace();
		}
		return retVal;

	}

	public Double getCost(){
		Double retVal = 0d;
		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			retVal = recipeJson.getDouble("Cost");
		}catch (Exception e){
			e.printStackTrace();
		}
		return retVal;


	}

	public void setArticleNumber(String s) {

		try {
			JSONObject recipeJson = new JSONObject(this.itemJson);
			recipeJson.put("artno",s);
			itemJson = recipeJson.toString();
		}catch (Exception e){
			e.printStackTrace();
		}

	}
}




