package com.certoclav.certoscale.database;


import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import org.json.JSONObject;



/*
{
    "_id": {
        "$oid": "58a1c719f36d2837a7c7456a"
    },
    "name": "Check Weigh ->Over Under",
    "userid": "",
    "devicekey": "93943649346387463",
    "date": "2014-06-25T00:00:00.000Z",
    "visibility": "private",
    "content": "BioLab GmbH\r\nExamplestreet 23\r\n8272 Munich\r\nGermany\r\n12/7/2010 3:32 PM\r\nBalance ID: 1202372\r\nBalance Name: EXPLORER SMART\r\nUser Name: michaeldirix@web.de\r\nProject Name:\r\nApplication: Check Weighing\r\nResult: Accept\r\nGross: 1.401 g\r\nNet: 0.455 g Net\r\nTare: 0.946 g \r\nOver Limit: 619.999 g\r\nUnder Limit: 0.010 g"
}
 */
/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "protocol")
public class Protocol {

	// id is generated by the database and set on the object automatically


	Protocol() {

	}


	public int getItem_id() {
		return item_id;
	}

	@DatabaseField(generatedId = true, columnName = "protocol_id")
	private int item_id;


	public String getProtocolJson() {
		return protocolJson;
	}

	public void setProtocolJson(String itemJson) {
		this.protocolJson = itemJson;
	}

	@DatabaseField(columnName = "protocol_json")
	private String protocolJson;

	public String generateProtocolJson(String name, String userEmail, String deviceKey, String date, boolean visibility, String content) {
		JSONObject jsonObject = new JSONObject();

		try {
			jsonObject
					.put("name", name)
					.put("userid", userEmail)
					.put("devicekey", deviceKey)
					.put("date", date)
					.put("visibility", visibility)
					.put("content", content);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return jsonObject.toString();
	}

	public Protocol(String cloudId, String protocolJson) {
		this.cloudId = cloudId;
		this.protocolJson = protocolJson;
	}

	public Protocol(String cloudId, String name, String userEmail, String deviceKey, String date, boolean visibility, String content) {
		this.cloudId = cloudId;
		this.protocolJson = generateProtocolJson(name, userEmail, deviceKey, date, visibility, content);
	}

	@DatabaseField(columnName = "cloud_id")
	private String cloudId;


	public String getUserEmail() {
		String retVal = "";

		try {
			JSONObject recipeJson = new JSONObject(this.protocolJson);
			retVal = recipeJson.getString("userid");
		} catch (Exception e) {
			e.printStackTrace();
		}
		return retVal;

	}


	public String getName() {
		String retVal = "";

		try {
			JSONObject recipeJson = new JSONObject(this.protocolJson);
			retVal = recipeJson.getString("name");
		} catch (Exception e) {
			e.printStackTrace();
		}
		return retVal;

	}


	public void setName(String name) {

		try {
			JSONObject recipeJson = new JSONObject(this.protocolJson);
			recipeJson.put("name", name);
			protocolJson = recipeJson.toString();
		} catch (Exception e) {
			e.printStackTrace();
		}


	}
}






