package com.certoclav.certoscale.model;

public enum ScaleApplication {
	WEIGHING,
	PART_COUNTING,
	PART_COUNTING_CALC_AWP,
	PERCENT_WEIGHING,
	PERCENT_WEIGHING_CALC_REFERENCE,
	CHECK_WEIGHING,
	ANIMAL_WEIGHING,
	FILLING,
	TOTALIZATION,
	FORMULATION,
	DIFFERENTIAL_WEIGHING,
	DENSITIY_DETERMINATION,
	PEAK_HOLD,
	INGREDIENT_COSTING,
	PIPETTE_ADJUSTMENT,
	STATISTICAL_QUALITY_CONTROL,

}
