package com.certoclav.certoscale.model;

public enum ScaleApplication {
	WEIGHING,
	PART_COUNTING,
	PART_COUNTING_CALC_AWP,
	PERCENT_WEIGHING,
	PERCENT_WEIGHING_CALC_REFERENCE,
	CHECK_WEIGHING,
	ANIMAL_WEIGHING,
	ANIMAL_WEIGHING_CALCULATING,
	FILLING,
	FILLING_CALC_TARGET,
	TOTALIZATION,
	FORMULATION,
	FORMULATION_RUNNING,

	FORMULATION_FREE,
	FORMULATION_FREE_RUNNING,

	DIFFERENTIAL_WEIGHING,
	DENSITY_DETERMINATION,
	DENSITY_DETERMINATION_STARTED,
	PEAK_HOLD,
	PEAK_HOLD_STARTED,
	INGREDIENT_COSTING,


	PIPETTE_ADJUSTMENT_1_HOME,
	PIPETTE_ADJUSTMENT_2_ACCEPT_ALL_SAMPLES,
	PIPETTE_ADJUSTMENT_3_FINISHED,




	STATISTICAL_QUALITY_CONTROL_1_HOME,
	STATISTICAL_QUALITY_CONTROL_2_BATCH_STARTED,
	STATISTICAL_QUALITY_CONTROL_3_BATCH_FINISHED,

	ASH_DETERMINATION_1_HOME,
	ASH_DETERMINATION_2_BATCH_STARTED,
    ASH_DETERMINATION_3_WEIGH_BEAKER,
	ASH_DETERMINATION_4_WEIGHING_SAMPLE, //state 4-7 are in a loop
	ASH_DETERMINATION_5_WAIT_FOR_GLOWING,
	ASH_DETERMINATION_6_WEIGHING_GLOWED_SAMPLE,
	ASH_DETERMINATION_7_CHECK_DELTA_WEIGHT,
	ASH_DETERMINATION_8_BATCH_FINISHED,
}
